import { useState, useEffect } from "react";

import Head from "next/head";
import styles from "../styles/Home.module.scss";

function Contador() {
  const count = "2022-07-24";
  const [days, setDays] = useState(0);
  const [hours, setHours] = useState(0);
  const [minutes, setMinutes] = useState(0);
  const [seconds, setSeconds] = useState(0);

  setInterval(() => {
    const dateNow = new Date().getTime();
    const dif = Date.parse(count) - dateNow;

    setDays(Math.floor(dif / (1000 * 60 * 60 * 24)));
    setHours(Math.floor((dif / (1000 * 60 * 60)) % 24));
    setMinutes(Math.floor((dif / 1000 / 60) % 60));
    setSeconds(Math.floor((dif / 1000) % 60));
  }, 1000);

  return (
    <>
      <ul className={styles.contador}>
        <li>
          <p className={styles.p}>Dias</p>
          {days}
        </li>
        :
        <li>
          <p className={styles.p}>Horas</p>
          {hours}
        </li>
        :
        <li>
          <p className={styles.p}>Minutos</p>
          {minutes}
        </li>
        :
        <li>
          <p className={styles.p}>Segundos</p>
          {seconds}
        </li>
      </ul>
    </>
  );
}

function Modal({ show, onClose }) {
  if (show) {
    return (
      <div className={styles.modal}>
        <div className={styles.modal__container}>
          <h1 className={styles.modal__title}>Inscreva-se</h1>
          <p className={styles.modal__p}>
            Digite seu nome e email para ser avisado quando for o dia
          </p>

          <form className={styles.form}>
            <input
              className={styles.form__inputT}
              type="text"
              placeholder="Nome"
              id="nome"
              name="nome"
            />
            <input
              className={styles.form__inputT}
              type="email"
              placeholder="Email"
              id="email"
              name="email"
            />

            <div className={styles.form__buttons}>
              <button
                className={styles.form__buttonC}
                onClick={(e) => {
                  e.preventDefault();
                  onClose();
                }}
              >
                Cancelar
              </button>
              <button className={styles.form__buttonE} type="submit">
                Enviar
              </button>
            </div>
          </form>
        </div>
      </div>
    );
  } else {
    return null;
  }
}

export default function Home() {
  const [showModal, setShowModal] = useState(false);

  return (
    <div>
      <Head>
        <title>Countdown</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <img src="/images/top-image.svg" alt="top images" />
      <main className={styles.main}>
        <div className={styles.text}>
          <h2 className={styles.title}>READY TO LAUNCH IN...</h2>
          <Contador />

          <p className={styles.subtitle}>
            Inscreva-se para saber mais sobre o lançamento
          </p>
          <button className={styles.button} onClick={() => setShowModal(true)}>
            Inscreva-se
          </button>
        </div>
        <img src="/images/rocket.svg" alt="Rocket" className={styles.rocket} />
      </main>
      <img
        src="/images/bottom-image.svg"
        alt="top images"
        className={styles.img_bottom}
      />

      <Modal
        show={showModal}
        onClose={() => {
          setShowModal(false);
        }}
      />
    </div>
  );
}
