import { useState } from "react";

import Head from "next/head";
import styles from "../styles/Home.module.scss";

function Contador() {
  const count = "2022-07-24";
  const [days, setDays] = useState(0);
  const [hours, setHours] = useState(0);
  const [minutes, setMinutes] = useState(0);
  const [seconds, setSeconds] = useState(0);

  setInterval(() => {
    const dateNow = new Date().getTime();
    const dif = Date.parse(count) - dateNow;

    setDays(Math.floor(dif / (1000 * 60 * 60 * 24)));
    setHours(Math.floor((dif / (1000 * 60 * 60)) % 24));
    setMinutes(Math.floor((dif / 1000 / 60) % 60));
    setSeconds(Math.floor((dif / 1000) % 60));
  }, 1000);

  return (
    <>
      <ul className={styles.contador}>
        <li>
          <p className={styles.p}>Dias</p>
          {days}
        </li>
        :
        <li>
          <p className={styles.p}>Horas</p>
          {hours}
        </li>
        :
        <li>
          <p className={styles.p}>Minutos</p>
          {minutes}
        </li>
        :
        <li>
          <p className={styles.p}>Segundos</p>
          {seconds}
        </li>
      </ul>
    </>
  );
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Countdown</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <img src="/images/top-image.svg" alt="top images" />
      <main className={styles.main}>
        <div className={styles.text}>
          <h2 className={styles.title}>READY TO LAUNCH IN...</h2>
          <Contador />

          <p className={styles.subtitle}>
            Inscreva-se para saber mais sobre o lançamento
          </p>
          <button className={styles.button}>Inscreva-se</button>
        </div>
        <img src="/images/rocket.svg" alt="Rocket" className={styles.rocket} />
      </main>
      <img
        src="/images/bottom-image.svg"
        alt="top images"
        className={styles.img_bottom}
      />
    </div>
  );
}
